# Hypothesis Test of the Means:


some points to keep in mind about p-value and hypothesis testing in general: 

• **The interpretation of the p-value :** 

it represents the prob of having a sample mean greater then the null value of H0 or, from  n random samples, given that the H0 is true  ( a conditionned probability ) 
In other words 
        P-value = P(extreme events in favor to alternative hypothesis  | H0 is true ) 



• High P-values: Your sample results are consistent with a true null hypothesis. <br>
• Low P-values: Your sample results are not consistent with a null hypothesis. <br>

• The significance level, also denoted as alpha or α, is the probability of rejecting the null  hypothesis when it is true


• Type 1 error : reject the H0 when the latter is true <br>
• Type 2 error : accept the H0 when the latter is false , in other words , we keep the H0 when we shouldn't <br>


• Type 1 error expressed with propability : 
  P-value = P(typ1 error |H0 is true ) = alpha 
  Increasing alpha -> increase error rate of making a type I error rate!



• **Goal of Increasing alpha (increase type 1 error) :** when we don't  want to fail to reject the H0 when the latter is false <br>
• **Goal of reducing alpha :** when we want to reject the H0 ONLY if we have STRONG evidence  favoring the Ha.



## One sample t-test:

In [115]:
import numpy as np
import scipy.stats as st
import pandas as pd

**Two-side test**

Question 1 : the goal of this exercice is to simulate one sample x with normal distribution

- step 1 : create n=10 random values using `np.random.randn` , note that this instruction returns z scores of standard normal
- step 2 : do the inverse transform to get x from these z scores using mu=3 and sigma=2 ( hint : use the forumla of z score ) and store the result in variable x
\begin{equation}
 z= \frac{x-\mu}{\sigma}
\end{equation}


- step 3 : we wish to test if the null hypothesis with a **two-side alternative hypothesis** , run the following and interpret the result , knowing that mu_0 is the mean of the null hypothesis 

``` 
mu_0 = 0
st.ttest_1samp(x, mu_0)

```

- step 4 : forumate the associated null hypothesis $H_{0}$ and alternative hypothesis $H_{a}$


In [97]:
#don't delete this line 

np.random.seed(1234)
n=10
z=np.random.randn(10)

mu=3
sigma=2
x = z * sigma + mu
print(" x ",x)
mu_0 = 0
print(st.ttest_1samp(x, mu_0))
st.t.ppf(0.025,df=n-1)
# significance level =  5%
#2.5% on the left, 2.5% on the right, coz we have two sides

 x  [ 3.94287033  0.61804861  5.86541394  2.37469621  1.55882253  4.77432588
  4.71917683  1.72695299  3.03139274 -1.48536991]
Ttest_1sampResult(statistic=3.8682023385794677, pvalue=0.0037991794351627216)


-2.262157162740992

Question 2 : now that you know how to use `st.ttest_1samp` , use the forumlas that you learnt during the course to get the same results , here's the step to follow : 

- step 1 : calculate the `mean` and the `standard error` $SE$ 
- step 2 : calculate the t-score using the following forumla :


\begin{equation}
  t = \frac{x-\bar{x} }{ \frac{S}{\sqrt{n} } }
\end{equation}

- step 3 : calculate the probability of `p-value` using `st.t.cdf` , remember that p-value = $2*P(X>tscore)$ 
  



In [98]:
def ttest_onesample(mu_0,alternative):
    print(mu_0)
    mean=x.mean()
    sem = x.std(ddof=1)/np.sqrt(n) #when working with a sample , always use ddof
    #the std of the sample is calculatd = sqrt(variance)
    #std = sqrt(variance)
    #variance = sum(x-x.mean())/(n-ddof) #here ddof = 1
    alpha = 0.05
    sig_level = alpha
    t = ((mean-mu_0)/(sem))
    if alternative =="two_tail":
        p_value = 2 * (1-st.t.cdf(t,df=len(x)-1)) #*2 coz we have two tails , always in sample stats : ddof = len(x)-1
        sig_level = alpha/2
    elif alternative =="left_tail":
        p_value = st.t.cdf(t,df=len(x)-1) 
    else:
        p_value =(1-st.t.cdf(t,df=len(x)-1)) 

    print(f"p-value {p_value}, t {t} , sig level alpha {sig_level}") #alpha/2 coz we have two tails


In [99]:
#Ha : m> mu0 we reject if p_value < significance level
#H0 : m <= m0
ttest_onesample(0,"right_tail") 

0
p-value 0.001899589717581418, t 3.8682023385794677 , sig level alpha 0.05


Question 3: same as the above but with `mu_0 = 1` , `mu_0 = 2` 


**right-tail test**

Question 4 : everything remain the same , except that the p-value is calculated differently , since : 

 p-value = $P(X>tscore)$ 


calculate the p-value with mu_0= 0 , mu_0= 1 , mu_0= 2 

In [116]:
ttest_onesample(1,alternative="right_tail")
print(st.ttest_1samp(x,0,alternative="less"))


1
p-value 1.65043240185625e-08, t 17.269010515793685 , sig level alpha 0.05


TypeError: ttest_1samp() got an unexpected keyword argument 'alternative'

In [ ]:
#mu of the population
#mu_0 what we wanna test
#H0: mu = mu_0, rejectes if p_value < sig level
#Ha : mu != mu_0
#we dont reject H0, coz p_value > sig level, we accept H0 that says mu = mu_0

In [101]:
ttest_onesample(2,"right_tail")
#we dont reject H0 since p_value>sig level, we accept that mu of population = mu0

2
p-value 0.16803373472127636, t 1.0162114374603375 , sig level alpha 0.05


**left-tail test**

Question 5 : everything remain the same , except that the p-value is calculated differently , since : 

 p-value = $P(X<tscore)$ 


calculate the p-value with mu_0= 0 , mu_0= 1 , mu_0= 2 

## independent two sample t-test

Question 6 : just like you created your samples in the first question , follow the same steps in order to create x1 and x2 that have the following propreties :

x1 (sample 1 ) : n1 = 10 , mu1 = 3 , sigma1 = 2

x2 (sample 2) :  n2 = 20 , mu2 = 5 , sigma2 = 3

In [102]:
#make sure to name your variables x1 and x2

n1=10
np.random.seed(1234)
z1 = np.random.randn(n1)
sigma1 = 2
mu1 = 3
x1 = z1*sigma1 + mu1

n2=20
np.random.seed(1234)
z2 = np.random.randn(n2)
sigma2 = 3
mu2 = 5

x2 = z2*sigma2 + mu2

Question 7 : run the following and interpret the results : 

In [103]:
st.ttest_ind(x1,x2,equal_var=False)                                       

Ttest_indResult(statistic=-2.2117261957242236, pvalue=0.036233352621873154)

Question 8 : calculate x1_mean , x2_mean  , s1 (unbiased standard deviation) , s2 of the two samples x1 and x2

In [104]:
m1 = x1.mean()
m2 = x2.mean()
s1 = x1.std(ddof=1)
s2 = x2.std(ddof=1)


Question 9 : run the function using the descriptive statistics optained in the previous question using  `st.ttest_ind_from_stats ` (i invite you to read the documentation first  ) , also make sure to set `equal_var=False`    

In [105]:
st.ttest_ind_from_stats(m1,s1,n1,m2,s2,n2,equal_var=False)

Ttest_indResult(statistic=-2.2117261957242236, pvalue=0.036233352621873154)

## Paired two sample t-test

Question 10 : Simulate two samples of size **n=10** with Normal distribution. to do so : 

- step 1 : create x1 using the same method as described in question1 with mu=3 , sigma=2
- step 2 : create a "noisy" distribution derived from x1 using the following formula : 
                    x2 = x1 + np.random.randn(n) + 1
                    
(Notice that the x2 is created by adding some 'noise' to the x1)

So,'one to one' relation is established.

In [106]:
n=500
np.random.seed(1234)
z = np.random.randn(n)
sigma = 2
mu = 3
x1 = z*sigma + mu


x2 = x1 +z + 1

In [24]:
x1.mean() , x2.mean()

(2.7126330151064457, 3.5689495226596697)

Question 11 : 
run the following line and interpret the results 


In [107]:
# Two tail test.
st.ttest_rel(x1,x2)
#The smaller is p value, means the samples are related 

Ttest_relResult(statistic=-23.507081770550556, pvalue=8.274574401234557e-83)

Question 12 : Compare with the indepdent two sample t-test on the same dataset. 


In [108]:
st.ttest_ind(x1,x2,equal_var=False)
#x1.mean(), x2.mean()
#here we only compare the mean
#to know if the samples have the sample stats (mean in this case)

Ttest_indResult(statistic=-6.519691435403449, pvalue=1.193163822997268e-10)

## ANOVA

There are three groups of students. The data corresponds to the test scores. Determine whether there is any significant difference in the group test scores.

In [41]:
# Data.
x1 = np.array([82,93,61,74,69,70,53])
x2 = np.array([71,62,85,94,78,66,71])
x3 = np.array([64,73,87,91,56,78,87])

In [42]:
# Using the f_onway() function from the SciPy library.
res=st.f_oneway(x1,x2,x3)
print("Test statistic  : %f " % res[0] )
print("p-value         : %f " % res[1] )
#p value = 0, means at least one is not equal

Test statistic  : 0.283726 
p-value         : 0.756278 


In [43]:
x1.mean(), x2.mean(), x3.mean()

(71.71428571428571, 75.28571428571429, 76.57142857142857)

# Summarizing categorical variables:

In [50]:
df = pd.read_csv('data_studentlist.csv', header='infer',encoding = 'latin1')

## Frequency table (One way table):

In [51]:
# Categorical variables.
bloodType = df['bloodtype']
gender = df['gender']

get the frequency table of bloodtype

In [54]:
FTB = bloodType.value_counts()

get the frequency table of gender

In [55]:
FTG = gender.value_counts()

get the normalized frequency table of bloodtype

In [69]:
bloodType.value_counts(normalize=True)

B     0.294118
O     0.294118
A     0.235294
AB    0.176471
Name: bloodtype, dtype: float64

same as the above for gender

In [70]:
gender.value_counts(normalize=True)

M    0.588235
F    0.411765
Name: gender, dtype: float64

##  Contingency table (Two way table):

get the Contingency table using `pd.crosstab`

In [66]:
pd.crosstab(index=df['bloodtype'], columns=df['gender'])

gender     F  M
bloodtype      
A          2  2
AB         1  2
B          1  4
O          3  2

in order to get Contingency table with marginalization , set the parameter `margins=True`


In [68]:
pd.crosstab(index=df['bloodtype'], columns=df['gender'],margins=True)

gender     F   M  All
bloodtype            
A          2   2    4
AB         1   2    3
B          1   4    5
O          3   2    5
All        7  10   17

# Hypothesis Test of proportions:
 

## Chi-squared Tests:

###  For one way table 

Suppose we have a frequency table of *eye color* of 592 adults. <br>
Let us carry out the Chi-squared tests.

- step 1  : create a series with data , and set the table `['Brown','Blue','Hazel','Green']` as index   

In [83]:
eye = pd.Series(data=data, index=['Brown','Blue','Hazel','Green'])
eye

Brown    220
Blue     215
Hazel     93
Green     64
dtype: int32

Question 13 : create a Table of proportions. to do so , divide your series by the sum of the frequencies

In [84]:
tab_proportions = eye / eye.sum()
tab_proportions

Brown    0.371622
Blue     0.363176
Hazel    0.157095
Green    0.108108
dtype: float64

Question 14 : Compare with the default model of equal frequencies. ( in other words , calculate the chisquare of your series using `st.chisquare`

In [85]:
st.chisquare(eye)

Power_divergenceResult(statistic=133.47297297297297, pvalue=9.650879774148268e-29)

Question 15 : the following is a model provided by the user that tries to approximate the frequencies 

In [87]:
my_model = len(eye)*[np.mean(eye)]
my_model

[148.0, 148.0, 148.0, 148.0]

run the following and describe the result :

In [88]:
st.chisquare(f_obs=eye,f_exp = my_model)

Power_divergenceResult(statistic=133.47297297297297, pvalue=9.650879774148268e-29)

In [ ]:
#since the p_value is smaller than the significance level = 0.05, we reject the null hypothesis

let's test with a more realistic model : 

In [90]:
my_model = eye.sum()*np.array([0.40,0.33,0.15,0.12])
my_model

array([236.8 , 195.36,  88.8 ,  71.04])

run the following and describe the result. what do you conlcude about the two proposed models ? 

In [91]:
st.chisquare(f_obs=eye,f_exp = my_model )

Power_divergenceResult(statistic=4.06265356265356, pvalue=0.25477767063672113)

In [ ]:
#conclusion about the two models: we notice that after multiplying the eye by the np.array, the values become different 
#after they were equal. And as a consequence, the p_value gets bigger (than the significance level = 0.05) 
#So we accept the null hypothesis (fail to reject H0)

##  For two way table:

Suppose we have a contingency table of *eye color* vs *hair color* of 592 adults. <br>
Let us carry out the Chi-squared test for independence.

In [92]:
# Data.
# Row label    = hair color.
# Column label = eye color. 
data_eye = {'Brown': [68,119,26,7], 'Blue':[20,84,17,94], 'Hazel':[15,54,14,10], 'Green':[5, 29, 14,16]}
data = pd.DataFrame(data_eye,index=['Black','Brown','Red','Blonde'])
data

Brown  Blue  Hazel  Green
Black      68    20     15      5
Brown     119    84     54     29
Red        26    17     14     14
Blonde      7    94     10     16

run the following to get Chi-square test of independence of variables in a contingency table. what do you conclude about the relationship between these two categorical variables ? 

In [93]:
st.chi2_contingency(data)

(138.28984162600824,
 2.325286787098839e-25,
 9,
 array([[ 40.13513514,  39.22297297,  16.96621622,  11.67567568],
        [106.28378378, 103.86824324,  44.92905405,  30.91891892],
        [ 26.38513514,  25.78547297,  11.15371622,   7.67567568],
        [ 47.19594595,  46.12331081,  19.95101351,  13.72972973]]))

In [ ]:
#The p_value is so small which means the variables are related (dependant)

Suppose we have a contingency table of the room class vs survived from RMS Titanic.
Let us carry out the Chi-squared test for independence.

In [94]:
# Data.
# Row label    = room class.
# Column label = survived. 
data_survived = {'Yes':[122, 167, 528, 673], 'No':[203,118,178,212]}
data = pd.DataFrame(data_survived,index=['1st','2nd','3rd','Crew'])
data

Yes   No
1st   122  203
2nd   167  118
3rd   528  178
Crew  673  212

run the following to get Chi-square test of independence of variables in a contingency table. what do you conclude about the relationship between these two categorical variables ? 

In [95]:
st.chi2_contingency(data)

(190.40110361683327,
 4.999927529868003e-41,
 3,
 array([[220.01363017, 104.98636983],
        [192.93502953,  92.06497047],
        [477.93730123, 228.06269877],
        [599.11403907, 285.88596093]]))

In [ ]:
#The p_value is so smaller than the significance level 0.05, which means that our variables are dependant, we reject H0